// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Coffee struct {
	ID        int64
	Name      string
	RoasterID int64
}

type Roaster struct {
	ID   int64
	Name string
}
